💄Add TextField with basic layout
nwingt/app-like-co pull request #1
Opened 2021-07-30 05:07 UTC by AuroraHuang22

1. Add TextField.vue & TextField.stories.ts
2. Update TextField with basic style
3. Modify tailwind.config variants

2021-08-02 02:14 UTC, nwingt commented
Please fix the typo in commit message of 3cc8d47

2021-08-02 02:47 UTC, nwingt commented on components/Button.stories.ts
> +      <template #append>append</template>
Should only keep `{{ title }}`

For demo of prepend/append slots, it is better to use another example

2021-08-02 02:47 UTC, nwingt commented on components/TextField.stories.ts
> +      description: 'Size of textfield, including height and font-weight',
```suggestion
      description: 'Size of TextField, including height and font-weight',
```

2021-08-02 02:48 UTC, nwingt commented
Please exclude Button related code from TextField commits

2021-08-02 03:25 UTC, nwingt requested changes

2021-08-02 03:25 UTC, nwingt commented on components/TextField.vue
> +    ]
Can use object too
```suggestion
    return {
      'border-[red] focus:border-red hover:border-red': this.errorMessage,
      'border-shade-gray': !this.errorMessage,
    }
```

2021-08-02 03:25 UTC, nwingt commented on components/TextField.vue
> +    return [{ 'text-[red] text-[10px] pl-[8px]': this.errorMessage }]
Can use object too
```suggestion
    return { 'text-[red] text-[10px] pl-[8px]': this.errorMessage }
```

2021-08-02 03:25 UTC, nwingt commented on tailwind.config.js
> +
What is this for 😂

2021-08-02 03:25 UTC, nwingt commented on components/TextField.vue
> +    'hover:border-like-cyan-light',
For class order, please reference to Tailwind documentation menu

2021-08-02 03:31 UTC, AuroraHuang22 commented on tailwind.config.js
> +
一陣混亂中 不小心出現的  🥺 
我來刪刪

2021-08-03 03:21 UTC, nwingt requested changes

2021-08-03 03:21 UTC, nwingt commented on components/TextField.stories.ts
> +    </div>`,
有兩個 TextField?

2021-08-03 03:21 UTC, nwingt commented on components/TextField.vue
> +    ]
如果只有一個 item，class name return 可以不用 array 包著
```suggestion
    return {
      'border-[red] focus:border-red hover:border-red': this.errorMessage,
      'border-shade-gray': !this.errorMessage,
    }
```

2021-08-03 03:23 UTC, nwingt commented on components/TextField.stories.ts
> +    </div>`,
可能 errorMessage default 是 empty string 比較好，然後多加一個 story 是有 errorMessage 的 😉

2021-08-03 04:07 UTC, AuroraHuang22 commented on components/TextField.vue
> +    ]
因為這個 return 會被使用在`rootClasses()`裡的 `...this.errorClasses`，如果不使用array包著的話，會報錯：
```
Invalid attempt to spread non-iterable instance.
```
所以我還是先用array包著

2021-08-03 04:52 UTC, AuroraHuang22 commented on components/TextField.vue
> +    ]
好滴👌

2021-08-04 04:04 UTC, nwingt requested changes

2021-08-04 04:04 UTC, nwingt commented on components/TextField.stories.ts
> +    </div>`,
可以把 Wrapper 搬到 `decorators`
```ts
export default {
  title: 'TextField',
  ...
  decorators: [() => ({ template: '<div class="w-[300px]"><story/></div>' })],
}
```
那 Template 可以更簡潔
```ts
const Template: = () => {
  template: `<TextField v-bind="$props" />`,
}
```

2021-08-04 04:09 UTC, AuroraHuang22 commented on components/TextField.stories.ts
> +})
👁👄👁 哇

2021-08-04 04:09 UTC, AuroraHuang22 commented on components/TextField.stories.ts
> +    </div>`,
👁👄👁 哇哇哇

2021-08-04 07:57 UTC, nwingt commented on components/TextField.stories.ts
> +    </div>`,
Button 的 Story 也可以參考這個哦

2021-08-04 08:28 UTC, AuroraHuang22 commented on components/TextField.stories.ts
> +    </div>`,
冇问题

2021-08-04 16:44 UTC, nwingt approved these changes

2021-08-04 16:44 UTC, merged