💄 Update Button component layouts
nwingt/app-like-co pull request #2
Opened 2021-08-03 09:23 UTC by AuroraHuang22

1. Add icon components
2. Add layout for prepend, both, append, circle state.
2. Update Button stories.

2021-08-04 01:55 UTC, nwingt requested changes

2021-08-04 01:55 UTC, nwingt commented on components/Button.stories.ts
> +        {{title}}
Please add space between JS value
```suggestion
        {{ title }}
```

2021-08-04 01:55 UTC, nwingt commented on components/Button.stories.ts
> +        {{title}}
Please add space between JS value
```suggestion
        {{ title }}
```

2021-08-04 01:55 UTC, nwingt commented on components/Button.stories.ts
> +// export const DropDown = Template.bind({})
Please remove if not needed

2021-08-04 01:55 UTC, nwingt commented on tailwind.config.js
>        white: 'white',
Please make white as `#FFF` and black `#000` 😆

2021-08-04 02:04 UTC, AuroraHuang22 commented on tailwind.config.js
>        white: 'white',
😂 yes sir

2021-08-04 02:18 UTC, nwingt requested changes

2021-08-04 02:18 UTC, nwingt commented on .eslintrc.js
> +    'import/extensions': 'off',
我調試過，這樣 config 應該較合適
```suggestion
    'array-bracket-newline': [
      'warn',
      { minItems: 2 },
    ],
    'array-element-newline': [
      'warn',
      "always",
    ],
    'comma-dangle': [
      'warn',
      'always-multiline',
    ],
    'import/extensions': 'off',
```

2021-08-04 02:18 UTC, nwingt commented on components/Button.vue
> +          },
如果是二選一，可以用 Conditional operator
```suggestion
          this.circle ? 'text-like-green' : 'text-dark-gray',
```

2021-08-04 02:18 UTC, nwingt commented on components/Button.vue
> +          },
同樣可以用 Conditional operator 簡化

2021-08-04 02:18 UTC, nwingt commented on components/Button.vue
> +            'text-dark-gray': !this.circle,
同樣可以用 Conditional operator 簡化

2021-08-04 02:18 UTC, nwingt commented on components/Button.vue
> +        }
同樣可以用 Conditional operator 簡化

2021-08-04 02:18 UTC, nwingt commented on components/Button.vue
> +        }
同樣可以用 Conditional operator 簡化

2021-08-04 16:43 UTC, nwingt commented on components/Button.vue
> +          ' bg-transparent',
```suggestion
          'bg-transparent',
```

2021-08-04 16:43 UTC, nwingt commented on components/Button.vue
> +          'flex-shrink', //
```suggestion
          'flex-shrink',
```

2021-08-04 16:43 UTC, nwingt commented on components/Button.vue
> +          'flex', //
```suggestion
          'flex',
```

2021-08-04 16:43 UTC, nwingt commented on components/Button.vue
> +      'flex-shrink', //
```suggestion
      'flex-shrink',
```

2021-08-04 16:43 UTC, nwingt commented on components/icons/ArrowDown.vue
> +</template>
Please add extra line break at the end of each file

2021-08-04 16:43 UTC, nwingt commented on components/Button.vue
> +        return [' bg-transparent']
```suggestion
        return ['bg-transparent']
```

2021-08-04 16:43 UTC, nwingt commented on components/Button.vue
> +          'bg-like-cyan-light', //
```suggestion
          'bg-like-cyan-light',
```

2021-08-04 16:43 UTC, nwingt commented on components/Button.stories.ts
> +        'large', //
```suggestion
        'large',
```

2021-08-04 16:43 UTC, nwingt commented on .eslintrc.js
> +      'warn', //
```suggestion
      'warn',
```

2021-08-04 16:43 UTC, nwingt commented on .eslintrc.js
> +      'warn', //
```suggestion
      'warn',
```

2021-08-04 16:59 UTC, AuroraHuang22 commented on components/Button.stories.ts
> +        ${args.append ? args.append : ''}
可以～我也蠻意外可以這樣寫的

2021-08-05 01:12 UTC, nwingt requested changes

2021-08-05 01:12 UTC, nwingt commented on components/Button.stories.ts
>        name: 'Preset',
直接用 props 的名字 OK 了 😉
```suggestion
```

2021-08-05 01:12 UTC, nwingt commented on components/Button.stories.ts
> +      name: 'Size',
同上
```suggestion
```

2021-08-05 01:12 UTC, nwingt commented on components/Button.stories.ts
> +      name: 'Disabled',
同上
```suggestion
```

2021-08-05 01:15 UTC, nwingt commented on components/Button.stories.ts
>  })
這樣改可以避免不必要的 props 注入
```ts
const PrependTemplate =
  `<template #prepend>
    <IconPlaceholder/>
  </template>`

const AppendTemplate =
  `<template #append>
    <ArrowDown/>
  </template>`

const Template: Story = (
  args: any,
  {
    argTypes: {
      title: _title,
      prepend: _prepend,
      append: _append,
      ...argTypes
    },
  }: any,
) => ({
  components: {
    IconPlaceholder,
    ArrowDown,
  },
  props: Object.keys(argTypes),
  template: `
    <Button v-bind="$props">
      ${args.prepend ? PrependTemplate : ''}
      ${args.title ? args.title : ''}
      ${args.append ? AppendTemplate : ''}
    </Button>
  `,
})
```

那下面的 Story 可以改成為
```ts
export const Both = Template.bind({})
Both.args = {
  ...Default.args,
  prepend: true,
  append: true,
}
```
如此類推

2021-08-05 13:26 UTC, nwingt requested changes
有些地方都多了空格

2021-08-05 13:26 UTC, nwingt commented on components/Button.stories.ts
> +          summay: 'string',
累了😂

2021-08-05 13:26 UTC, nwingt commented on components/Button.stories.ts
> +  text:'Title',
```suggestion
  text: 'Title',
```

2021-08-05 13:26 UTC, nwingt commented on components/Button.stories.ts
> +  customSlot:true,
```suggestion
  customSlot: true,
```

2021-08-05 13:26 UTC, nwingt commented on components/Button.vue
> +      </div>
```suggestion
      <div v-if="$slots.default" :class="contentWrapperClasses">
        <slot/>
      </div>
      <div v-else :class="contentWrapperClasses">
        {{ text }}
      </div>
```

2021-08-06 03:04 UTC, nwingt requested changes

2021-08-06 03:04 UTC, nwingt commented on components/Button.stories.ts
> +        'primary',
這裏多了一個 space

2021-08-06 03:04 UTC, nwingt commented on components/Button.vue
> -      </div>
Vue 不支援像 JSX 用 inline if
```suggestion
      <div v-if="$slots.default" :class="contentWrapperClasses">
        <slot/>
      </div>
      <div v-else :class="contentWrapperClasses">
        {{ text }}
      </div>
```

2021-08-06 03:28 UTC, nwingt approved these changes

2021-08-06 03:30 UTC, merged