💄[component] Add FormField
nwingt/app-like-co pull request #3
Opened 2021-08-06 11:54 UTC by AuroraHuang22

1. Add FormField.vue & FormField.stories.ts.
2. Update with text, bold, link, textField, tags layout

2021-08-09 02:03 UTC, nwingt requested changes

2021-08-09 02:03 UTC, nwingt commented on components/icons/LinkTo.vue
> +<template>
Icon 命名可參考 https://fonts.google.com/icons?icon.query=north+east

2021-08-09 06:09 UTC, nwingt requested changes

2021-08-10 02:28 UTC, nwingt requested changes

2021-08-10 02:28 UTC, nwingt commented on components/FormField.stories.ts
> +  </template>`
如果是 default slot, 可以不用額外 template 包著

2021-08-10 02:28 UTC, nwingt commented on components/FormField.stories.ts
> +  </template>`
同上

2021-08-10 02:28 UTC, nwingt commented on components/FormField.stories.ts
> +  </template>`
同上

2021-08-10 02:28 UTC, nwingt commented on components/FormField.stories.ts
> +  </template>`
同上

2021-08-10 02:28 UTC, nwingt commented on components/FormField.stories.ts
> +  </template>`
同上

2021-08-10 02:28 UTC, nwingt commented on components/FormField.stories.ts
> +  </template>`
同上

2021-08-10 02:28 UTC, nwingt commented on components/FormField.vue
> +        return []
建議加一個 `custom`，等同 default

2021-08-10 02:28 UTC, nwingt commented on components/Link.vue
> +      this.to,
為什麼加 `this.to`?

2021-08-10 02:28 UTC, nwingt commented on components/Tag.vue
> +      this.text,
為什麼加 `this.text`

2021-08-10 06:01 UTC, nwingt requested changes

2021-08-10 06:01 UTC, nwingt commented on components/FormField.stories.ts
> +    <div class='font-normal text-[16px] leading-[21.79px]'>
用約數 leading-[22px]

2021-08-10 06:01 UTC, nwingt commented on components/FormField.stories.ts
> +    <Tag text='tag name'/>
Template 內用 `"`

2021-08-10 06:01 UTC, nwingt commented on components/FormField.stories.ts
> +  label: 'Url',
URL 我 prefer 全大寫

2021-08-10 06:02 UTC, AuroraHuang22 commented on components/Link.vue
> +      'leading-[21.79px]',
🥲

2021-08-10 08:29 UTC, nwingt approved these changes

2021-08-10 08:30 UTC, merged